<a href="https://colab.research.google.com/github/anuragpatil811/Machine-Learning/blob/main/Heart_Disease_Data_Imbalance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

In [6]:
df = pd.read_csv('/content/heart_disease_data.csv')

In [7]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [8]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [9]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
x = df.drop('target', axis=1)
y = df['target']

In [13]:
ov = RandomOverSampler()
x_ov, y_ov = ov.fit_resample(x, y)

In [14]:
y_ov.value_counts()

target
1    165
0    165
Name: count, dtype: int64

In [15]:
us = RandomUnderSampler()
usx, usy = us.fit_resample(x, y)
usy.value_counts()

target
0    138
1    138
Name: count, dtype: int64

In [16]:
sm = SMOTE()
smx, smy = sm.fit_resample(x, y)
smy.value_counts()

target
1    165
0    165
Name: count, dtype: int64