<a href="https://colab.research.google.com/github/anuragpatil811/Machine-Learning/blob/main/Test_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
sen = ['He is Abhishek', 'Abhishek is second in the class', 'Ritesh is third in the class', 'Is he Abhishek?' ]

In [6]:
#Count Vectorizer
cv = CountVectorizer()

In [7]:
cv.fit(sen)

CountVectorizer()

In [8]:
cv.vocabulary_

{'he': 2,
 'is': 4,
 'abhishek': 0,
 'second': 6,
 'in': 3,
 'the': 7,
 'class': 1,
 'ritesh': 5,
 'third': 8}

In [9]:
cv.get_feature_names_out()

array(['abhishek', 'class', 'he', 'in', 'is', 'ritesh', 'second', 'the',
       'third'], dtype=object)

In [10]:
x = cv.fit_transform(sen)

In [11]:
x.toarray()

array([[1, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0]])

In [12]:
pd.DataFrame(data=x.toarray(), columns = cv.get_feature_names_out())

   abhishek  class  he  in  is  ritesh  second  the  third
0         1      0   1   0   1       0       0    0      0
1         1      1   0   1   1       0       1    1      0
2         0      1   0   1   1       1       0    1      1
3         1      0   1   0   1       0       0    0      0

In [14]:
#TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

In [15]:
tf.fit(sen)

TfidfVectorizer()

In [17]:
y = tf.fit_transform(sen)

In [18]:
y.toarray()

array([[0.55953044, 0.        , 0.69113141, 0.        , 0.4574528 ,
        0.        , 0.        , 0.        , 0.        ],
       [0.33902999, 0.41876949, 0.        , 0.41876949, 0.27717923,
        0.        , 0.53115599, 0.41876949, 0.        ],
       [0.        , 0.38761905, 0.        , 0.38761905, 0.25656108,
        0.49164562, 0.        , 0.38761905, 0.49164562],
       [0.55953044, 0.        , 0.69113141, 0.        , 0.4574528 ,
        0.        , 0.        , 0.        , 0.        ]])

In [19]:
tf.get_feature_names_out()

array(['abhishek', 'class', 'he', 'in', 'is', 'ritesh', 'second', 'the',
       'third'], dtype=object)

In [20]:
pd.DataFrame(data = y.toarray(), columns=tf.get_feature_names_out())

,abhishek,class,he,in,is,ritesh,second,the,third
0,0.55953,0.000000,0.691131,0.000000,0.457453,0.000000,0.000000,0.000000,0.000000
1,0.33903,0.418769,0.000000,0.418769,0.277179,0.000000,0.531156,0.418769,0.000000
2,0.00000,0.387619,0.000000,0.387619,0.256561,0.491646,0.000000,0.387619,0.491646
3,0.55953,0.000000,0.691131,0.000000,0.457453,0.000000,0.000000,0.000000,0.000000